FROM ubuntu:jammy-20240627.1

#RUN apt update \
#  && apt install -y build-essential cmake clang-format clang-tidy lcov libbenchmark-dev libclang-dev libgoogle-perftools-dev python3 python3-pip python-is-python3 \
#  && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

