version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
          - "github/*"
      github-owned-actions:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/plugins/bmqprometheus
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/sanitizers
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/plugins/bmqprometheus/tests/docker
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /src/python
    schedule:
      interval: daily
