libbmq: BloombergLP::bmqa::ConfigureQueueStatus Class Reference
BloombergLP::bmqa::ConfigureQueueStatus Class Reference
#include <bmqa_configurequeuestatus.h>
Public Member Functions
ConfigureQueueStatus (bslma::Allocator *allocator=0)
Default constructor, use the optionally specified allocator.
ConfigureQueueStatus (const bmqa::ConfigureQueueStatus &other, bslma::Allocator *allocator=0)
ConfigureQueueStatus (const QueueId &queueId, bmqt::ConfigureQueueResult::Enum result, const bsl::string &errorDescription, bslma::Allocator *allocator=0)
ConfigureQueueStatus & operator= (const ConfigureQueueStatus &rhs)
operator bool () const
Return true if this result indicates success, and false otherwise.
const QueueId & queueId () const
Return the queueId associated to this operation result, if any.
bmqt::ConfigureQueueResult::Enum result () const
const bsl::string & errorDescription () const
bsl::ostream & print (bsl::ostream &stream, int level=0, int spacesPerLevel=4) const
Detailed Description
A value-semantic type for a configure queue operation with the message queue broker.
Constructor & Destructor Documentation
ConfigureQueueStatus() [1/3]
BloombergLP::bmqa::ConfigureQueueStatus::ConfigureQueueStatus (bslma::Allocator * allocator = 0) inline explicit
ConfigureQueueStatus() [2/3]
BloombergLP::bmqa::ConfigureQueueStatus::ConfigureQueueStatus (const bmqa::ConfigureQueueStatus & other, bslma::Allocator * allocator = 0) inline
Create a new bmqa::ConfigureQueueStatus using the optionally specified allocator.
ConfigureQueueStatus() [3/3]
BloombergLP::bmqa::ConfigureQueueStatus::ConfigureQueueStatus (const QueueId & queueId, bmqt::ConfigureQueueResult::Enum result, const bsl::string & errorDescription, bslma::Allocator * allocator = 0) inline
Create a new bmqa::ConfigureQueueStatus object having the specified queueId, result, and errorDescription, using the optionally specified allocator to supply memory.
Member Function Documentation
operator=()
ConfigureQueueStatus & BloombergLP::bmqa::ConfigureQueueStatus::operator= (const ConfigureQueueStatus & rhs) inline
Assign to this ConfigureQueueStatus the same values as the one from the specified rhs.
References errorDescription(), queueId(), and result().
operator bool()
BloombergLP::bmqa::ConfigureQueueStatus::operator bool () const inline
References BloombergLP::bmqt::ConfigureQueueResult::e_SUCCESS.
queueId()
const QueueId & BloombergLP::bmqa::ConfigureQueueStatus::queueId () const inline
Referenced by operator=(), and BloombergLP::bmqa::operator==().
result()
bmqt::ConfigureQueueResult::Enum BloombergLP::bmqa::ConfigureQueueStatus::result () const inline
Return the result code that indicates success or the cause of a failure.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
errorDescription()
const bsl::string & BloombergLP::bmqa::ConfigureQueueStatus::errorDescription () const inline
Return a printable description of the error, if result indicates failure. Return an empty string otherwise.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
print()
bsl::ostream & BloombergLP::bmqa::ConfigureQueueStatus::print (bsl::ostream & stream, int level = 0, int spacesPerLevel = 4) const
Format this object to the specified output stream at the (absolute value of) the optionally specified indentation level and return a reference to stream. If level is specified, optionally specify spacesPerLevel, the number of spaces per indentation level for this and all of its nested objects. If level is negative, suppress indentation of the first line. If spacesPerLevel is negative format the entire output on one line, suppressing all but the initial indentation (as governed by level). If stream is not valid on entry, this operation has no effect.
Referenced by BloombergLP::bmqa::operator<<().
The documentation for this class was generated from the following file:
bmqa/bmqa_configurequeuestatus.h