libbmq: BloombergLP::bmqa::CloseQueueStatus Class Reference
BloombergLP::bmqa::CloseQueueStatus Class Reference
#include <bmqa_closequeuestatus.h>
Public Types
typedef bsls::UnspecifiedBool< CloseQueueStatus >::BoolType BoolType
Public Member Functions
CloseQueueStatus (bslma::Allocator *allocator=0)
Default constructor, use the optionally specified allocator.
CloseQueueStatus (const bmqa::CloseQueueStatus &other, bslma::Allocator *allocator=0)
CloseQueueStatus (const QueueId &queueId, bmqt::CloseQueueResult::Enum result, const bsl::string &errorDescription, bslma::Allocator *allocator=0)
CloseQueueStatus & operator= (const CloseQueueStatus &rhs)
operator BoolType () const
Return true if this result indicates success, and false otherwise.
const QueueId & queueId () const
Return the queueId associated to this operation result, if any.
bmqt::CloseQueueResult::Enum result () const
const bsl::string & errorDescription () const
bsl::ostream & print (bsl::ostream &stream, int level=0, int spacesPerLevel=4) const
Detailed Description
A value-semantic type for a close queue operation with the message queue broker.
Member Typedef Documentation
BoolType
typedef bsls::UnspecifiedBool<CloseQueueStatus>::BoolType BloombergLP::bmqa::CloseQueueStatus::BoolType
Constructor & Destructor Documentation
CloseQueueStatus() [1/3]
BloombergLP::bmqa::CloseQueueStatus::CloseQueueStatus (bslma::Allocator * allocator = 0) inline explicit
CloseQueueStatus() [2/3]
BloombergLP::bmqa::CloseQueueStatus::CloseQueueStatus (const bmqa::CloseQueueStatus & other, bslma::Allocator * allocator = 0) inline
Create a new bmqa::CloseQueueStatus using the optionally specified allocator.
CloseQueueStatus() [3/3]
BloombergLP::bmqa::CloseQueueStatus::CloseQueueStatus (const QueueId & queueId, bmqt::CloseQueueResult::Enum result, const bsl::string & errorDescription, bslma::Allocator * allocator = 0) inline
Create a new bmqa::CloseQueueStatus object having the specified queueId, result, and errorDescription, using the optionally specified allocator to supply memory.
Member Function Documentation
operator=()
CloseQueueStatus & BloombergLP::bmqa::CloseQueueStatus::operator= (const CloseQueueStatus & rhs) inline
Assign to this CloseQueueStatus the same values as the one from the specified rhs.
References errorDescription(), queueId(), and result().
operator BoolType()
BloombergLP::bmqa::CloseQueueStatus::operator BoolType () const inline
References BloombergLP::bmqt::CloseQueueResult::e_SUCCESS.
queueId()
const QueueId & BloombergLP::bmqa::CloseQueueStatus::queueId () const inline
Referenced by operator=(), and BloombergLP::bmqa::operator==().
result()
bmqt::CloseQueueResult::Enum BloombergLP::bmqa::CloseQueueStatus::result () const inline
Return the status code that indicates success or the cause of a failure.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
errorDescription()
const bsl::string & BloombergLP::bmqa::CloseQueueStatus::errorDescription () const inline
Return a printable description of the error, if result indicates failure. Return an empty string otherwise.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
print()
bsl::ostream & BloombergLP::bmqa::CloseQueueStatus::print (bsl::ostream & stream, int level = 0, int spacesPerLevel = 4) const
Format this object to the specified output stream at the (absolute value of) the optionally specified indentation level and return a reference to stream. If level is specified, optionally specify spacesPerLevel, the number of spaces per indentation level for this and all of its nested objects. If level is negative, suppress indentation of the first line. If spacesPerLevel is negative format the entire output on one line, suppressing all but the initial indentation (as governed by level). If stream is not valid on entry, this operation has no effect.
Referenced by BloombergLP::bmqa::operator<<().
The documentation for this class was generated from the following file:
bmqa/bmqa_closequeuestatus.h