libbmq: BloombergLP::bmqa::OpenQueueStatus Class Reference
BloombergLP::bmqa::OpenQueueStatus Class Reference
#include <bmqa_openqueuestatus.h>
Public Types
typedef bsls::UnspecifiedBool< OpenQueueStatus >::BoolType BoolType
Public Member Functions
OpenQueueStatus (bslma::Allocator *allocator=0)
Default constructor, use the optionally specified allocator.
OpenQueueStatus (const bmqa::OpenQueueStatus &other, bslma::Allocator *allocator=0)
OpenQueueStatus (const QueueId &queueId, bmqt::OpenQueueResult::Enum result, const bsl::string &errorDescription, bslma::Allocator *allocator=0)
OpenQueueStatus & operator= (const OpenQueueStatus &rhs)
Assignment operator from the specified rhs.
operator BoolType () const
Return true if this result indicates success, and false otherwise.
const QueueId & queueId () const
Return the queueId associated to this operation result, if any.
bmqt::OpenQueueResult::Enum result () const
const bsl::string & errorDescription () const
bsl::ostream & print (bsl::ostream &stream, int level=0, int spacesPerLevel=4) const
Detailed Description
A value-semantic type for an open queue operation with the message queue broker.
Member Typedef Documentation
BoolType
typedef bsls::UnspecifiedBool<OpenQueueStatus>::BoolType BloombergLP::bmqa::OpenQueueStatus::BoolType
Use of an UnspecifiedBool to prevent implicit conversions to integral values, and comparisons between different classes which have boolean operators.
Constructor & Destructor Documentation
OpenQueueStatus() [1/3]
BloombergLP::bmqa::OpenQueueStatus::OpenQueueStatus (bslma::Allocator * allocator = 0) inline explicit
OpenQueueStatus() [2/3]
BloombergLP::bmqa::OpenQueueStatus::OpenQueueStatus (const bmqa::OpenQueueStatus & other, bslma::Allocator * allocator = 0) inline
Create a new bmqa::OpenQueueStatus using the optionally specified allocator.
OpenQueueStatus() [3/3]
BloombergLP::bmqa::OpenQueueStatus::OpenQueueStatus (const QueueId & queueId, bmqt::OpenQueueResult::Enum result, const bsl::string & errorDescription, bslma::Allocator * allocator = 0) inline
Create a new bmqa::OpenQueueStatus object having the specified queueId, result, and errorDescription, using the optionally specified allocator to supply memory.
Member Function Documentation
operator=()
OpenQueueStatus & BloombergLP::bmqa::OpenQueueStatus::operator= (const OpenQueueStatus & rhs) inline
References errorDescription(), queueId(), and result().
operator BoolType()
BloombergLP::bmqa::OpenQueueStatus::operator BoolType () const inline
References BloombergLP::bmqt::OpenQueueResult::e_SUCCESS.
queueId()
const QueueId & BloombergLP::bmqa::OpenQueueStatus::queueId () const inline
Referenced by operator=(), and BloombergLP::bmqa::operator==().
result()
bmqt::OpenQueueResult::Enum BloombergLP::bmqa::OpenQueueStatus::result () const inline
Return the result code that indicates success or the cause of a failure.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
errorDescription()
const bsl::string & BloombergLP::bmqa::OpenQueueStatus::errorDescription () const inline
Return a printable description of the error, if result indicates failure. Return an empty string otherwise.
Referenced by operator=(), and BloombergLP::bmqa::operator==().
print()
bsl::ostream& BloombergLP::bmqa::OpenQueueStatus::print (bsl::ostream & stream, int level = 0, int spacesPerLevel = 4) const
Format this object to the specified output stream at the (absolute value of) the optionally specified indentation level and return a reference to stream. If level is specified, optionally specify spacesPerLevel, the number of spaces per indentation level for this and all of its nested objects. If level is negative, suppress indentation of the first line. If spacesPerLevel is negative format the entire output on one line, suppressing all but the initial indentation (as governed by level). If stream is not valid on entry, this operation has no effect.
Referenced by BloombergLP::bmqa::operator<<().
The documentation for this class was generated from the following file:
bmqa/bmqa_openqueuestatus.h