libbmq: BloombergLP::bmqt::Version Class Reference
BloombergLP::bmqt::Version Class Reference
A version consisting of a major and minor version number.
#include <bmqt_version.h>
Public Member Functions
Version ()
Version (unsigned char major, unsigned char minor)
Version & setMajor (unsigned char value)
Version & setMinor (unsigned char value)
bsl::ostream & print (bsl::ostream &stream, int level=0, int spacesPerLevel=4) const
unsigned char major () const
Return the major part of the version.
unsigned char minor () const
Return the minor part of the version.
Constructor & Destructor Documentation
Version() [1/2]
BloombergLP::bmqt::Version::Version () inline
Create an object of type Version having the default value. Note that major is set to zero and minor is set to zero.
Version() [2/2]
BloombergLP::bmqt::Version::Version (unsigned char major, unsigned char minor) inline
Create an object of type Version initialized with the specified major and minor versions.
Member Function Documentation
setMajor()
Version & BloombergLP::bmqt::Version::setMajor (unsigned char value) inline
Set the major part of the version to the specified value and return a reference to this object.
setMinor()
Version & BloombergLP::bmqt::Version::setMinor (unsigned char value) inline
Set the minor part of the version to the specified value and return a reference to this object.
print()
bsl::ostream & BloombergLP::bmqt::Version::print (bsl::ostream & stream, int level = 0, int spacesPerLevel = 4) const
Format this object to the specified output stream at the optionally specified indentation level and return a reference to the modifiable stream. If level is specified, optionally specify spacesPerLevel, the number of spaces per indentation level for this and all of its nested objects. Each line is indented by the absolute value of level * spacesPerLevel. If level is negative, suppress indentation of the first line. If spacesPerLevel is negative, suppress line breaks and format the entire output on one line. If stream is initially invalid, this operation has no effect. Note that a trailing newline is provided in multiline mode only.
Referenced by BloombergLP::bmqt::operator<<().
major()
unsigned char BloombergLP::bmqt::Version::major () const inline
Referenced by BloombergLP::bmqt::operator!=(), BloombergLP::bmqt::operator<(), and BloombergLP::bmqt::operator==().
minor()
unsigned char BloombergLP::bmqt::Version::minor () const inline
Referenced by BloombergLP::bmqt::operator!=(), BloombergLP::bmqt::operator<(), and BloombergLP::bmqt::operator==().
The documentation for this class was generated from the following file:
bmqt/bmqt_version.h