libbmq: BloombergLP::bmqa::ConfirmEventBuilder Class Reference
BloombergLP::bmqa::ConfirmEventBuilder Class Reference
Mechanism to build a batch of CONFIRM messages.
#include <bmqa_confirmeventbuilder.h>
Public Member Functions
ConfirmEventBuilder ()
~ConfirmEventBuilder ()
Destroy this instance.
bmqt::EventBuilderResult::Enum addMessageConfirmation (const Message &message)
bmqt::EventBuilderResult::Enum addMessageConfirmation (const MessageConfirmationCookie &cookie)
void reset ()
int messageCount () const
const bdlbb::Blob & blob () const
Constructor & Destructor Documentation
ConfirmEventBuilder()
BloombergLP::bmqa::ConfirmEventBuilder::ConfirmEventBuilder () inline
Create an invalid instance. Application should not create ConfirmEventBuilder themselves, but ask the bmqa::Session to give them one, by using bmqa::Session::loadConfirmEventBuilder.
~ConfirmEventBuilder()
BloombergLP::bmqa::ConfirmEventBuilder::~ConfirmEventBuilder ()
Member Function Documentation
addMessageConfirmation() [1/2]
bmqt::EventBuilderResult::Enum BloombergLP::bmqa::ConfirmEventBuilder::addMessageConfirmation (const Message & message) inline
Append a confirmation message for the specified message. Return zero on success, and a non-zero value otherwise. Behavior is undefined unless this instance was obtained using bmqa::Session::loadConfirmEventBuilder.
References addMessageConfirmation(), and BloombergLP::bmqa::Message::confirmationCookie().
Referenced by addMessageConfirmation().
addMessageConfirmation() [2/2]
bmqt::EventBuilderResult::Enum BloombergLP::bmqa::ConfirmEventBuilder::addMessageConfirmation (const MessageConfirmationCookie & cookie)
Append a confirmation message for the specified MessageConfirmationCookie cookie. Return zero on success, and a non-zero value otherwise. Behavior is undefined unless this instance was obtained using bmqa::Session::loadConfirmEventBuilder.
reset()
void BloombergLP::bmqa::ConfirmEventBuilder::reset ()
Reset the builder, effectively discarding the batch of confirmation messages under construction.
messageCount()
int BloombergLP::bmqa::ConfirmEventBuilder::messageCount () const
Return the number of messages currently in the ConfirmEvent being built. Behavior is undefined unless this instance was obtained using bmqa::Session::loadConfirmEventBuilder.
blob()
const bdlbb::Blob & BloombergLP::bmqa::ConfirmEventBuilder::blob () const
Return a reference not offering modifiable access to the blob of confirmation messages batch built by this builder. If no messages were added, this will return an empty blob, i.e., a blob with length == 0. Behavior is undefined unless this instance was obtained using bmqa::Session::loadConfirmEventBuilder.
The documentation for this class was generated from the following file:
bmqa/bmqa_confirmeventbuilder.h