libbmq: BloombergLP::bmqa Namespace Reference
BloombergLP::bmqa Namespace Reference
Classes
class AbstractSession
A pure protocol for a session.
class CloseQueueStatus
class ConfigureQueueStatus
class ConfirmEventBuilder
Mechanism to build a batch of CONFIRM messages.
class Event
A variant type encompassing all types of events.
class ManualHostHealthMonitor
class Message
A message sent/received to/from the BlazingMQ broker.
class MessageConfirmationCookie
Cookie for async message confirmation.
class MessageEvent
class MessageEventBuilder
A builder for MessageEvent objects.
class MessageIterator
class MessageProperties
Provide a VST representing message properties.
class MessagePropertiesIterator
class MockSession
Mechanism to mock a bmqa::Session
struct MockSessionUtil
Utility methods to create bmqa events.
class OpenQueueStatus
class QueueId
Value-semantic efficient identifier for a queue.
class Session
A session with a BlazingMQ broker.
class SessionEvent
An event related to the operation of a Session.
class SessionEventHandler
Functions
bool operator== (const CloseQueueStatus &lhs, const CloseQueueStatus &rhs)
bool operator!= (const CloseQueueStatus &lhs, const CloseQueueStatus &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const CloseQueueStatus &rhs)
bool operator== (const ConfigureQueueStatus &lhs, const ConfigureQueueStatus &rhs)
bool operator!= (const ConfigureQueueStatus &lhs, const ConfigureQueueStatus &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const ConfigureQueueStatus &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const Event &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const Message &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const MessageEvent &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const MessageProperties &rhs)
bool operator== (const OpenQueueStatus &lhs, const OpenQueueStatus &rhs)
bool operator!= (const OpenQueueStatus &lhs, const OpenQueueStatus &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const OpenQueueStatus &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const QueueId &rhs)
bool operator== (const QueueId &lhs, const QueueId &rhs)
bool operator!= (const QueueId &lhs, const QueueId &rhs)
bool operator< (const QueueId &lhs, const QueueId &rhs)
bool operator== (const SessionEvent &lhs, const SessionEvent &rhs)
bool operator!= (const SessionEvent &lhs, const SessionEvent &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const SessionEvent &rhs)
Function Documentation
operator==() [1/5]
bool BloombergLP::bmqa::operator== (const CloseQueueStatus & lhs, const CloseQueueStatus & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqa::CloseQueueStatus::errorDescription(), BloombergLP::bmqa::CloseQueueStatus::queueId(), and BloombergLP::bmqa::CloseQueueStatus::result().
operator!=() [1/5]
bool BloombergLP::bmqa::operator!= (const CloseQueueStatus & lhs, const CloseQueueStatus & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
operator<<() [1/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const CloseQueueStatus & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::CloseQueueStatus::print().
operator==() [2/5]
bool BloombergLP::bmqa::operator== (const ConfigureQueueStatus & lhs, const ConfigureQueueStatus & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqa::ConfigureQueueStatus::errorDescription(), BloombergLP::bmqa::ConfigureQueueStatus::queueId(), and BloombergLP::bmqa::ConfigureQueueStatus::result().
operator!=() [2/5]
bool BloombergLP::bmqa::operator!= (const ConfigureQueueStatus & lhs, const ConfigureQueueStatus & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
operator<<() [2/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const ConfigureQueueStatus & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::ConfigureQueueStatus::print().
operator<<() [3/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const Event & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::Event::print().
operator<<() [4/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const Message & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::Message::print().
operator<<() [5/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const MessageEvent & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::MessageEvent::print().
operator<<() [6/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const MessageProperties & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::MessageProperties::print().
operator==() [3/5]
bool BloombergLP::bmqa::operator== (const OpenQueueStatus & lhs, const OpenQueueStatus & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqa::OpenQueueStatus::errorDescription(), BloombergLP::bmqa::OpenQueueStatus::queueId(), and BloombergLP::bmqa::OpenQueueStatus::result().
operator!=() [3/5]
bool BloombergLP::bmqa::operator!= (const OpenQueueStatus & lhs, const OpenQueueStatus & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
operator<<() [7/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const OpenQueueStatus & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::OpenQueueStatus::print().
operator<<() [8/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const QueueId & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::QueueOptions::print().
operator==() [4/5]
bool BloombergLP::bmqa::operator== (const QueueId & lhs, const QueueId & rhs) inline
Return true if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return false otherwise.
operator!=() [4/5]
bool BloombergLP::bmqa::operator!= (const QueueId & lhs, const QueueId & rhs) inline
Return false if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return true otherwise.
operator<()
bool BloombergLP::bmqa::operator< (const QueueId & lhs, const QueueId & rhs) inline
Operator used to allow comparison between the specified lhs and rhs CorrelationId objects so that CorrelationId can be used as key in a map.
operator==() [5/5]
bool BloombergLP::bmqa::operator== (const SessionEvent & lhs, const SessionEvent & rhs)
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
operator!=() [5/5]
bool BloombergLP::bmqa::operator!= (const SessionEvent & lhs, const SessionEvent & rhs)
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
operator<<() [9/9]
bsl::ostream & BloombergLP::bmqa::operator<< (bsl::ostream & stream, const SessionEvent & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqa::SessionEvent::print().