libbmq: BloombergLP::bmqt Namespace Reference
BloombergLP::bmqt Namespace Reference
Classes
struct AckResult
This enum represents the result code status of an ack message.
struct CloseQueueResult
This enum represents the result of a closeQueue operation.
struct CompressionAlgorithmType
This struct defines various types of compression algorithms.
struct ConfigureQueueResult
This enum represents the result of a configureQueue operation.
class CorrelationId
struct CorrelationIdLess
struct EncodingType
Enumeration for message encoding types.
struct EventBuilderResult
struct GenericResult
This enum represents generic common status.
struct HostHealthState
Enumeration for host health states.
struct MessageEventType
Enumeration for the types of message events.
class MessageGUID
class MessageGUIDHashAlgo
struct MessageGUIDLess
This struct provides a binary function for comparing 2 GUIDs.
struct OpenQueueResult
This enum represents the result of an openQueue operation.
struct PostResult
This enum represents the result code status of a post message.
struct PropertyType
This enum represents the supported data types for a message property.
struct QueueFlags
This enum represents queue flags.
struct QueueFlagsUtil
class QueueOptions
Value-semantic type for options related to a queue.
struct SessionEventType
Enumeration for the types of session events.
class SessionOptions
class Subscription
Value-semantic type to carry Subscription parameters.
class SubscriptionExpression
Value-semantic type to carry Subscription criteria.
class SubscriptionHandle
Value-semantic type for unique Subscription id.
class Uri
Value semantic type representing a URI.
class UriBuilder
struct UriParser
Utility namespace of methods for parsing URI strings into Uri objects.
class Version
A version consisting of a major and minor version number.
Functions
bsl::ostream & operator<< (bsl::ostream &stream, CompressionAlgorithmType::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, const CorrelationId &rhs)
bool operator== (const CorrelationId &lhs, const CorrelationId &rhs)
bool operator!= (const CorrelationId &lhs, const CorrelationId &rhs)
bool operator< (const CorrelationId &lhs, const CorrelationId &rhs)
template<class HASH_ALGORITHM >
void hashAppend (HASH_ALGORITHM &hashAlgo, const CorrelationId &value)
bsl::ostream & operator<< (bsl::ostream &stream, EncodingType::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, HostHealthState::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, MessageEventType::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, const MessageGUID &rhs)
bool operator== (const MessageGUID &lhs, const MessageGUID &rhs)
bool operator!= (const MessageGUID &lhs, const MessageGUID &rhs)
bool operator< (const MessageGUID &lhs, const MessageGUID &rhs)
template<class HASH_ALGORITHM >
void hashAppend (HASH_ALGORITHM &hashAlgo, const MessageGUID &guid)
bsl::ostream & operator<< (bsl::ostream &stream, PropertyType::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, QueueFlags::Enum value)
bool operator== (const QueueOptions &lhs, const QueueOptions &rhs)
bool operator!= (const QueueOptions &lhs, const QueueOptions &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const QueueOptions &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, GenericResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, OpenQueueResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, ConfigureQueueResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, CloseQueueResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, EventBuilderResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, AckResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, PostResult::Enum value)
bsl::ostream & operator<< (bsl::ostream &stream, SessionEventType::Enum value)
bool operator== (const SessionOptions &lhs, const SessionOptions &rhs)
bool operator!= (const SessionOptions &lhs, const SessionOptions &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const SessionOptions &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const SubscriptionHandle &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const Subscription &rhs)
template<class HASH_ALGORITHM >
void hashAppend (HASH_ALGORITHM &hashAlgo, const SubscriptionHandle &id)
Apply the specified hashAlgo to the specified id.
bool operator< (const SubscriptionHandle &lhs, const SubscriptionHandle &rhs)
bool operator== (const SubscriptionHandle &lhs, const SubscriptionHandle &rhs)
bool operator!= (const SubscriptionHandle &lhs, const SubscriptionHandle &rhs)
bool operator== (const Uri &lhs, const Uri &rhs)
bool operator!= (const Uri &lhs, const Uri &rhs)
bool operator< (const Uri &lhs, const Uri &rhs)
bsl::ostream & operator<< (bsl::ostream &stream, const Uri &rhs)
template<class HASH_ALGORITHM >
void hashAppend (HASH_ALGORITHM &hashAlgo, const Uri &uri)
bsl::ostream & operator<< (bsl::ostream &stream, const Version &rhs)
bool operator== (const Version &lhs, const Version &rhs)
bool operator!= (const Version &lhs, const Version &rhs)
bool operator< (const Version &lhs, const Version &rhs)
Function Documentation
operator<<() [1/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, CompressionAlgorithmType::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::CompressionAlgorithmType::print().
operator<<() [2/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const CorrelationId & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::CorrelationId::print().
operator==() [1/7]
bool BloombergLP::bmqt::operator== (const CorrelationId & lhs, const CorrelationId & rhs) inline
Return true if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return false otherwise.
operator!=() [1/7]
bool BloombergLP::bmqt::operator!= (const CorrelationId & lhs, const CorrelationId & rhs) inline
Return false if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return true otherwise.
operator<() [1/5]
bool BloombergLP::bmqt::operator< (const CorrelationId & lhs, const CorrelationId & rhs) inline
Operator used to allow comparison between the specified lhs and rhs CorrelationId objects so that CorrelationId can be used as key in a map.
hashAppend() [1/4]
template<class HASH_ALGORITHM > void BloombergLP::bmqt::hashAppend (HASH_ALGORITHM & hashAlgo, const CorrelationId & value)
operator<<() [3/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, EncodingType::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
operator<<() [4/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, HostHealthState::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
operator<<() [5/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, MessageEventType::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
operator<<() [6/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const MessageGUID & rhs) inline
Write the value of the specified rhs object to the specified output stream in a human-readable format, and return a reference to stream. Note that this human-readable format is not fully specified, and can change without notice. Applications relying on a fixed length format must use toHex method.
References BloombergLP::bmqt::MessageGUID::print().
operator==() [2/7]
bool BloombergLP::bmqt::operator== (const MessageGUID & lhs, const MessageGUID & rhs) inline
Return true if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return false otherwise.
operator!=() [2/7]
bool BloombergLP::bmqt::operator!= (const MessageGUID & lhs, const MessageGUID & rhs) inline
Return false if rhs object contains the value of the same type as contained in lhs object and the value itself is the same in both objects, return true otherwise.
operator<() [2/5]
bool BloombergLP::bmqt::operator< (const MessageGUID & lhs, const MessageGUID & rhs) inline
Return true if the specified lhs instance is smaller than the specified rhs instance, false otherwise. Note that criteria for comparison is implementation defined, and result of this routine does not in any way signify the order of creation/arrival/delivery of messages to which lhs and rhs instances belong. Note that this operator is provided so that MessageGUID can be used as a key in associative containers (map, set, etc).
hashAppend() [2/4]
template<class HASH_ALGORITHM > void BloombergLP::bmqt::hashAppend (HASH_ALGORITHM & hashAlgo, const MessageGUID & guid)
operator<<() [7/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, PropertyType::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::PropertyType::print().
operator<<() [8/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, QueueFlags::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::QueueFlags::print().
operator==() [3/7]
bool BloombergLP::bmqt::operator== (const QueueOptions & lhs, const QueueOptions & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqt::QueueOptions::consumerPriority(), BloombergLP::bmqt::QueueOptions::maxUnconfirmedBytes(), BloombergLP::bmqt::QueueOptions::maxUnconfirmedMessages(), and BloombergLP::bmqt::QueueOptions::suspendsOnBadHostHealth().
operator!=() [3/7]
bool BloombergLP::bmqt::operator!= (const QueueOptions & lhs, const QueueOptions & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
References BloombergLP::bmqt::QueueOptions::consumerPriority(), BloombergLP::bmqt::QueueOptions::maxUnconfirmedBytes(), BloombergLP::bmqt::QueueOptions::maxUnconfirmedMessages(), and BloombergLP::bmqt::QueueOptions::suspendsOnBadHostHealth().
operator<<() [9/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const QueueOptions & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::QueueOptions::print().
operator<<() [10/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, GenericResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::GenericResult::print().
operator<<() [11/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, OpenQueueResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::OpenQueueResult::print().
operator<<() [12/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, ConfigureQueueResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::ConfigureQueueResult::print().
operator<<() [13/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, CloseQueueResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::CloseQueueResult::print().
operator<<() [14/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, EventBuilderResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::EventBuilderResult::print().
operator<<() [15/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, AckResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::AckResult::print().
operator<<() [16/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, PostResult::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::PostResult::print().
operator<<() [17/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, SessionEventType::Enum value) inline
Format the specified value to the specified output stream and return a reference to the modifiable stream.
operator==() [4/7]
bool BloombergLP::bmqt::operator== (const SessionOptions & lhs, const SessionOptions & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqt::SessionOptions::blobBufferSize(), BloombergLP::bmqt::SessionOptions::brokerUri(), BloombergLP::bmqt::SessionOptions::channelHighWatermark(), BloombergLP::bmqt::SessionOptions::closeQueueTimeout(), BloombergLP::bmqt::SessionOptions::configureQueueTimeout(), BloombergLP::bmqt::SessionOptions::connectTimeout(), BloombergLP::bmqt::SessionOptions::eventQueueHighWatermark(), BloombergLP::bmqt::SessionOptions::eventQueueLowWatermark(), BloombergLP::bmqt::SessionOptions::hostHealthMonitor(), BloombergLP::bmqt::SessionOptions::numProcessingThreads(), BloombergLP::bmqt::SessionOptions::openQueueTimeout(), BloombergLP::bmqt::SessionOptions::statsDumpInterval(), BloombergLP::bmqt::SessionOptions::traceContext(), and BloombergLP::bmqt::SessionOptions::tracer().
operator!=() [4/7]
bool BloombergLP::bmqt::operator!= (const SessionOptions & lhs, const SessionOptions & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
References BloombergLP::bmqt::SessionOptions::blobBufferSize(), BloombergLP::bmqt::SessionOptions::brokerUri(), BloombergLP::bmqt::SessionOptions::channelHighWatermark(), BloombergLP::bmqt::SessionOptions::closeQueueTimeout(), BloombergLP::bmqt::SessionOptions::configureQueueTimeout(), BloombergLP::bmqt::SessionOptions::connectTimeout(), BloombergLP::bmqt::SessionOptions::eventQueueHighWatermark(), BloombergLP::bmqt::SessionOptions::eventQueueLowWatermark(), BloombergLP::bmqt::SessionOptions::hostHealthMonitor(), BloombergLP::bmqt::SessionOptions::numProcessingThreads(), BloombergLP::bmqt::SessionOptions::openQueueTimeout(), BloombergLP::bmqt::SessionOptions::statsDumpInterval(), BloombergLP::bmqt::SessionOptions::traceContext(), and BloombergLP::bmqt::SessionOptions::tracer().
operator<<() [18/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const SessionOptions & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::SessionOptions::print().
operator<<() [19/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const SubscriptionHandle & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::SubscriptionHandle::print().
operator<<() [20/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const Subscription & rhs) inline
References BloombergLP::bmqt::Subscription::print().
hashAppend() [3/4]
template<class HASH_ALGORITHM > void BloombergLP::bmqt::hashAppend (HASH_ALGORITHM & hashAlgo, const SubscriptionHandle & id)
operator<() [3/5]
bool BloombergLP::bmqt::operator< (const SubscriptionHandle & lhs, const SubscriptionHandle & rhs) inline
operator==() [5/7]
bool BloombergLP::bmqt::operator== (const SubscriptionHandle & lhs, const SubscriptionHandle & rhs) inline
operator!=() [5/7]
bool BloombergLP::bmqt::operator!= (const SubscriptionHandle & lhs, const SubscriptionHandle & rhs) inline
operator==() [6/7]
bool BloombergLP::bmqt::operator== (const Uri & lhs, const Uri & rhs) inline
Return true if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return false otherwise.
References BloombergLP::bmqt::Uri::asString().
operator!=() [6/7]
bool BloombergLP::bmqt::operator!= (const Uri & lhs, const Uri & rhs) inline
Return false if the specified rhs object contains the value of the same type as contained in the specified lhs object and the value itself is the same in both objects, return true otherwise.
References BloombergLP::bmqt::Uri::asString().
operator<() [4/5]
bool BloombergLP::bmqt::operator< (const Uri & lhs, const Uri & rhs) inline
Return true if the specified lhs object compares less than the specified rhs object.
References BloombergLP::bmqt::Uri::asString().
operator<<() [21/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const Uri & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::Uri::print().
hashAppend() [4/4]
template<class HASH_ALGORITHM > void BloombergLP::bmqt::hashAppend (HASH_ALGORITHM & hashAlgo, const Uri & uri)
operator<<() [22/22]
bsl::ostream & BloombergLP::bmqt::operator<< (bsl::ostream & stream, const Version & rhs) inline
Format the specified rhs to the specified output stream and return a reference to the modifiable stream.
References BloombergLP::bmqt::Version::print().
operator==() [7/7]
bool BloombergLP::bmqt::operator== (const Version & lhs, const Version & rhs) inline
Return true if the object in the specified lhs represents the same version as the one in the specified rhs, return false otherwise.
References BloombergLP::bmqt::Version::major(), and BloombergLP::bmqt::Version::minor().
operator!=() [7/7]
bool BloombergLP::bmqt::operator!= (const Version & lhs, const Version & rhs) inline
Return true if the object in the specified lhs represents a different version than the one in the specified rhs, return false otherwise.
References BloombergLP::bmqt::Version::major(), and BloombergLP::bmqt::Version::minor().
operator<() [5/5]
bool BloombergLP::bmqt::operator< (const Version & lhs, const Version & rhs) inline
Return true if the version represented by the specified lhs is less than the version represented by the specified rhs.
References BloombergLP::bmqt::Version::major(), and BloombergLP::bmqt::Version::minor().