libbmq: BloombergLP::bmqt::CorrelationIdLess Struct Reference
BloombergLP::bmqt::CorrelationIdLess Struct Reference
#include <bmqt_correlationid.h>
Public Member Functions
bool operator() (const CorrelationId &lhs, const CorrelationId &rhs) const
Member Function Documentation
operator()()
bool BloombergLP::bmqt::CorrelationIdLess::operator() (const CorrelationId & lhs, const CorrelationId & rhs) const inline
Return true if the specified lhs should be considered as having a value less than the specified rhs.
References BloombergLP::bmqt::CorrelationId::isAutoValue(), BloombergLP::bmqt::CorrelationId::isNumeric(), BloombergLP::bmqt::CorrelationId::isPointer(), BloombergLP::bmqt::CorrelationId::isSharedPtr(), BloombergLP::bmqt::CorrelationId::theNumeric(), BloombergLP::bmqt::CorrelationId::thePointer(), and BloombergLP::bmqt::CorrelationId::theSharedPtr().
The documentation for this struct was generated from the following file:
bmqt/bmqt_correlationid.h