#! /usr/bin/env bash

set -e

repo_dir=$(realpath "$0")
repo_dir=${repo_dir%/src/*}

export PYTHONPATH=$repo_dir/src/python:$PYTHONPATH
cd "$repo_dir/src/integration-tests"

for type in single multi; do
    for wave in {1..10} 0; do
        python -m pytest -vv "--bmq-wave=$wave" \
            -m "$type and not csl_mode and not fsm_mode" "$@" \
            | grep -v SKIPPED
    done
done
