name: Pytest coverage

on:
  schedule:
    # Generate Pytest coverage report.
    - cron: "5 0 * * *"

  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"
      - "edited"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  python_unit_tests_coverage:
    name: UT coverage [python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Generate Python Unit Tests Coverage report
        env:
          PYTHONPATH: ${{ github.workspace }}/src/python
        run: |
          pip install -r ${{ github.workspace }}/src/python/requirements-test.txt
          cd ${{ github.workspace }}/src/python
          pytest --cov blazingmq \
            --cov-report term \
            --cov-report html:python-coverage \
            --cov-report xml:python-coverage.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: code-coverage-report
          path: |
            ${{ github.workspace }}/src/python/python-coverage
            ${{ github.workspace }}/src/python/python-coverage.xml
