name: Pytest coverage

on:
  schedule:
    # Generate Pytest coverage report.
    - cron: "5 0 * * *"

  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"
      - "edited"

  workflow_dispatch:
    inputs:
      uploadArtifact:
        description: 'Generate report and upload artifact'
        required: true
        type: 'boolean'
        default: 'true'

jobs:
  python_unit_tests_coverage:
    name: UT coverage [python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Python Unit Tests Coverage report
        env:
          PYTHONPATH: ${{ github.workspace }}/src/python
        run: |
          pip install -r ${{ github.workspace }}/src/python/requirements.txt
          cd ${{ github.workspace }}/src/python
          pytest --cov blazingmq \
            --cov-report term \
            --cov-report html:python-coverage \
            --cov-report xml:python-coverage.xml

      - name: Archive code coverage results
        if: ${{ github.event.workflow_dispatch && inputs.uploadArtifact }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            ${{ github.workspace }}/src/python/python-coverage
            ${{ github.workspace }}/src/python/python-coverage.xml
