name: Sanitize

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build_and_run_sanitizer:
    name: ${{ matrix.mode }}${{ matrix.fuzz == 'on' && '-fuzz' || '' }}
    strategy:
      matrix:
        mode: ["asan", "msan", "tsan", "ubsan"]
        fuzz: ["off"]
        include:
          - mode: "asan"
            fuzz: "on"
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Purge runner
      # Strip the runner to avoid space quota exceeding
        run: |
          echo "=== Disk usage before purge ==="
          df -h /
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/.ghcup
          sudo docker image prune --all --force
          echo "=== Disk usage after purge ==="
          df -h /
      - name: Build [${{ github.job }}]
        run: |
          docker build -f ${{ github.workspace }}/docker/sanitizers/Dockerfile \
          --no-cache --build-arg SANITIZER_NAME=${{ matrix.mode }} --build-arg \
          FUZZER=${{ matrix.fuzz }} -t sanitizer-${{ github.job }} .
      - name: UT [c++,${{ github.job }}]
        if: ${{ matrix.fuzz == 'off' }}
        run: docker run --rm sanitizer-${{ github.job }}
      - name: IT [c++,${{ github.job }}]
        if: ${{ matrix.fuzz == 'off' }}
        run: |
          docker run --rm sanitizer-${{ github.job }} /blazingmq/cmake.bld/Linux/run-it.sh -k breathing --bmq-tolerate-dirty-shutdown
