name: Build and run Sanitizer

on:
  workflow_call:
    inputs:
      sanitizer-name:
        description: Sanitizer name (asan/msan/tsan/ubsan)
        type: string
        required: true

jobs:
  build_and_run_sanitizer:
    name: Build and run Sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      -name : Cleanup image
        # run: sudo apt-get update && sudo apt-get purge -y gcc-* clang-* ruby-* swift-* kotlin-* julia-* nodejs-* && sudo apt-get autoremove -y && sudo rm -rf /var/lib/apt/lists/*
        run: sudo apt-get update && sudo apt-get purge -y gcc-*

      - name: Create docker image with BlazingMQ and dependencies built with sanitizer instrumentation
        run: docker build -f ${{ github.workspace }}/docker/sanitizers/Dockerfile --no-cache --build-arg SANITIZER_NAME=${{ inputs.sanitizer-name }} -t sanitizer-${{ inputs.sanitizer-name }} .
       
      - name: Run docker container with unit tests under sanitizer
        run: docker run sanitizer-${{ inputs.sanitizer-name }}
