name: Build and run Sanitizer

on:
  workflow_call:
    inputs:
      sanitizer-name:
        description: Sanitizer name (asan/msan/tsan/ubsan)
        type: string
        required: true

jobs:
  build_and_run_sanitizer:
    name: Build and run Sanitizer
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check disk space
        run: df . -h

      - name : Remove unneeded packages to avoid runner quota exceeding.
        run: |
          sudo apt-get purge \
          azure-cli microsoft-edge-stable google-cloud-cli \
          google-chrome-stable temurin-21-jdk temurin-17-jdk \
          temurin-11-jdk dotnet-sdk-8.0 firefox temurin-8-jdk \
          powershell libllvm17t64 libllvm18 libllvm16t64 \
          openjdk-21-jre-headless mysql-server-core-8.0
          sudo apt-get autoremove
          sudo apt-get autoclean

      - name: Check disk space after cleanup
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
          df . -h

      - name: Create docker image with BlazingMQ and dependencies built with sanitizer instrumentation
        run: | 
          docker build -f ${{ github.workspace }}/docker/sanitizers/Dockerfile \
          --no-cache --build-arg SANITIZER_NAME=${{ inputs.sanitizer-name }} \
          -t sanitizer-${{ inputs.sanitizer-name }} .
       
      - name: Run docker container with unit tests under sanitizer
        run: docker run --rm sanitizer-${{ inputs.sanitizer-name }}
