name: Sanitizers

on:
  workflow_call:
    inputs:
      sanitizer-name:
        description: Sanitizer name (asan/msan/tsan/ubsan)
        type: string
        required: true
      # working-directory:
      #   description: Working directory to use
      #   type: string
      #   default: './'

jobs:
  build_and_run_sanitizer:
    name: Build and run Sanitizer
    runs-on: ubuntu-22.04
    # defaults:
    #   run:
    #     working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Get dependencies hash
        id: get-hash
        run: echo "deps_hash=`cat docker/build_deps.sh | shasum`" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v4
        with:
          path: deps
          key: deps-${{ steps.get-hash.outputs.deps_hash }}
      # - name: San name
      #   run: echo ${{ inputs.sanitizer-name }}
      # - name: ROOT name
      #   run: pwd
      - name: Build BlazingMQ and dependencies with sanitizer instrumentation
        run: ./.github/workflows/sanitizers/build_sanitizer.sh ${{ inputs.sanitizer-name }}
      - name: Cat run-env.sh
        run: cat ${{ github.workspace }}/cmake.bld/Linux/run-env.sh
      - name: Cat run-unittests.sh
        run: cat ${{ github.workspace }}/cmake.bld/Linux/run-unittests.sh
      - name: List build
        run: ls -lah ${{ github.workspace }}/cmake.bld/Linux
      - name: List test binaries
        run: find ${{ github.workspace }}/cmake.bld/Linux -name "*.t.tsk"
      - name: Run unit tests under sanitizer
        run: ${{ github.workspace }}/cmake.bld/Linux/run-unittests.sh
